version: "3"
services:
  sharetribe:
    container_name: italiawork-sharetribe
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment: 
      - NODE_ENV=production
      - PORT=3000
    ports:
      - 3000:3000