name: deploy-server
run-name: Deploy server
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - server/**
      - package.json
      - yarn.lock
      - .github/workflows/build-and-deploy-sharetribe.yaml
      - Dockerfile
      - docker-compose.yaml
concurrency: 
  group: main
  cancel-in-progress: true
jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@v1.0.0
        if: github.ref_name == 'main'
        with:
          host: 165.232.117.209
          username: root
          key:  ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/italiawork;
            git stash;
            git checkout ${{ github.ref_name }};
            git pull origin ${{ github.ref_name }} --ff-only;
            docker-compose up -d;
            echo y | docker system prune -a;